Doxygen for BNDLYR.f
NOAA-EMC/UPP pull request #408
Opened 2021-10-25 20:02 UTC by hertneky

This is part of Issue #392 
Fixes the doxygen warnings in BNDLYR.f.

2021-10-25 20:10 UTC, hertneky commented
@edwardhartnett One question for you. Is there a standard of how to document a subroutine that has no Inputs or outputs. BNDLYR.f has no inputs, so I did not add anything for that. But, I could add 'param[in] None'. Please advise - thanks!

2021-10-25 20:59 UTC, edwardhartnett requested changes

2021-10-25 20:59 UTC, edwardhartnett commented on sorc/ncep_post.fd/BNDLYR.f
> +!> OTHER FIELDS MAY BE COMPUTED.
Convert to proper case, so it's not all SHOUTING!

2021-10-25 20:59 UTC, edwardhartnett commented on sorc/ncep_post.fd/BNDLYR.f
> +!> @param[out] QCNVBND - LAYER MOISTURE CONVERGENCE IN NBL.
The last two parameters are out of order. They should be documented in the order they appear in the subroutine declaration.

2021-10-25 21:00 UTC, edwardhartnett commented
@hertneky it's OK if there's no [in] parameters. Just document what is there. If there's no in, there's no in, and that's OK. ;-)

2021-10-25 21:24 UTC, edwardhartnett commented on sorc/ncep_post.fd/BNDLYR.f
> +!> ***WARNING*** If you change parameter NBND in this routine
Instead of ***WARNING*** you can use @note.

This will create a "note" in the documentation, which will stand out from the rest.

2021-10-25 21:24 UTC, edwardhartnett approved these changes

2021-10-25 21:25 UTC, hertneky commented on sorc/ncep_post.fd/BNDLYR.f
> +!> OTHER FIELDS MAY BE COMPUTED.
@edwardhartnett Ha - I was actually wondering about that - made that change.

2021-10-25 21:26 UTC, hertneky commented on sorc/ncep_post.fd/BNDLYR.f
> +!> @param[out] QCNVBND - LAYER MOISTURE CONVERGENCE IN NBL.
@edwardhartnett Fixed - hadn't even thought to check - thanks!

2021-10-25 21:34 UTC, hertneky commented on sorc/ncep_post.fd/BNDLYR.f
> +!> ***WARNING*** If you change parameter NBND in this routine
I like it. Changed to using @note

2021-10-27 19:35 UTC, WenMeng-NOAA commented
@hertneky Can you sync your branch with upstream/develop? Your PR would be the next one for reviewing, testing and merging. Thanks!

2021-10-27 20:58 UTC, hertneky commented
@WenMeng-NOAA  Sync'd and tested on Hera

2021-10-28 13:30 UTC, WenMeng-NOAA approved these changes

2021-10-28 13:31 UTC, WenMeng-NOAA commented
This PR is for documentation enhancement. There are no impact on the UPP regression tests.

2021-10-28 13:32 UTC, merged