Port UPP develop branch on wcoss2
NOAA-EMC/UPP pull request #439
Opened 2022-01-22 00:31 UTC by WenMeng-NOAA

Add changes in UPP develop branch for WCOSS2.

2022-01-24 14:00 UTC, KateFriedman-NOAA requested changes
Changes look good and match similar changes done during the WCOSS2 port. 

One requested change: please convert the wcoss2 modulefile to LUA format and build in the version overrides, like what was done during the ops side of the WCOSS2 port. Also, if you haven't started already, please consider converting any other machine modulefiles to LUA format to be consistent across platforms (in a separate issue/PR). Thanks!

2022-01-24 14:14 UTC, WenMeng-NOAA commented
> Changes look good and match similar changes done during the WCOSS2 port.
> 
> One requested change: please convert the wcoss2 modulefile to LUA format and build in the version overrides, like what was done during the ops side of the WCOSS2 port. Also, if you haven't started already, please consider converting any other machine modulefiles to LUA format to be consistent across platforms (in a separate issue/PR). Thanks!

@KateFriedman-NOAA With modulefile in LUA format, where the following settings should be configurated for CMAKE build:
```
setenv CC cc
setenv CXX CC
setenv FC ftn
```
Thanks!

2022-01-24 16:18 UTC, WenMeng-NOAA commented
@kgerheiser I saw the following warning from Cmake build during linking:
```
[100%] Linking Fortran executable upp.x
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: warning: libjpeg.so.62, needed by /apps/spack/jasper/2.0.25/intel/19.1.3.304/sjib74krrorkyczqpqah4tvewmlnqdx4/lib64/libjasper.so, may conflict with libjpeg.so.9
```
I have to add "load  module libjpeg/9c" in the runtime job card. Do you have any suggestions on it? Thanks!

2022-01-24 22:17 UTC, WenMeng-NOAA commented
@KateFriedman-NOAA I change modulefile on wcoss2 in LUA format and might updates other modulefiles in the future.

2022-01-25 13:16 UTC, KateFriedman-NOAA commented
> @KateFriedman-NOAA I change modulefile on wcoss2 in LUA format and might updates other modulefiles in the future.

Thanks @WenMeng-NOAA !

2022-02-02 16:23 UTC, EdwardColon-NOAA approved these changes
These updates look good.

2022-02-02 16:24 UTC, EdwardColon-NOAA approved these changes

2022-02-02 16:24 UTC, EdwardColon-NOAA approved these changes

2022-02-02 16:25 UTC, EdwardColon-NOAA approved these changes

2022-02-02 16:26 UTC, EdwardColon-NOAA approved these changes

2022-02-02 16:26 UTC, EdwardColon-NOAA approved these changes

2022-02-02 16:35 UTC, EricRogers-NOAA reviewed
Why not add cactus as well in ./tests/detect_machine.sh?

2022-02-02 16:50 UTC, BinLiu-NOAA approved these changes
Thanks for porting UPP to WCOSS2! Changes look good to me.

2022-02-02 17:11 UTC, WenMeng-NOAA commented
> Why not add cactus as well in ./tests/detect_machine.sh?

@EricRogers-NOAA Good catching. Added for cactus and wcoss1 P3.5". Thanks!

2022-02-02 17:35 UTC, EricRogers-NOAA commented
Thanks, the rest looks fine.

2022-02-02 17:46 UTC, EricRogers-NOAA approved these changes

2022-02-02 17:58 UTC, KateFriedman-NOAA approved these changes
Looks good, thanks @WenMeng-NOAA !

2022-02-02 18:15 UTC, merged