Lambert update
NOAA-EMC/UPP pull request #45
Opened 2020-01-09 18:19 UTC by JiliDong-NOAA

update for:

1) library update for jet
2) update for write component coordinate change
3) update for post library

2020-01-09 18:51 UTC, climbfuji commented
@fossell @junwang-noaa @JiliDong-NOAA do we need the changes in sorc/ncep_post.fd/INITPOST_NETCDF.f for the UFS public release? None of the others should be required according to my limited knowledge. Thanks!

2020-01-09 20:10 UTC, WenMeng-NOAA commented
@climbfuji This changes are for regional FV3 only. No need to sync to the UFS public release.

2020-01-21 00:55 UTC, WenMeng-NOAA requested changes

2020-01-21 00:55 UTC, WenMeng-NOAA commented on sorc/ncep_post.fd/grib2_module.f
> +       ifield3(14) = 48         !Resolution and component flags
It would be better for changing fv3 related  model with earth relative.

2020-01-21 00:55 UTC, WenMeng-NOAA commented on sorc/ncep_post.fd/grib2_module.f
> +
It would be better for changing fv3 related to model with earth relative only.

2020-01-21 18:58 UTC, JiliDong-NOAA commented on sorc/ncep_post.fd/grib2_module.f
> +       ifield3(14) = 48         !Resolution and component flags
merged the change to separate FV3 and HRRR/RUC for grib2 wind output

2020-01-22 05:16 UTC, WenMeng-NOAA approved these changes

2020-01-22 05:25 UTC, WenMeng-NOAA commented
The regression tests were conducted on Dell, Cray and Hera. The changes were expected.

2020-01-22 05:26 UTC, merged