Update community run script
NOAA-EMC/UPP pull request #491
Opened 2022-05-05 03:49 UTC by kayeekayee

run_upp script got the following updates:
-updated directory name from EMC_post to UPP
-updated executable path to tests/install/bin
-added error message for binarynemsiompiio option
-added netcdfpara option

Able to run all 6 cases on Cheyenne with Intel option.

2022-05-05 13:28 UTC, fossell commented
This PR fixes #492

2022-05-05 13:33 UTC, fossell commented
@kayeekayee - Have these changes been tested?

2022-05-05 16:10 UTC, hertneky requested changes
Some additional mods that couldn't be added in review:

L38 EMC-post -> UPP
L95-97: remove debug comment and extra whitespace
L298 -> LAM add netcdfpara as well

2022-05-05 16:10 UTC, hertneky commented on scripts/run_upp
>  #                 LAM - "netcdf"
With the unification - both GFS and LAM support netcdfpara

2022-05-05 16:10 UTC, hertneky commented on scripts/run_upp
>     if [[ ${inFormat} == "binarynemsiompiio" ]]; then
What about just removing this part of the if statement altogether?

2022-05-05 16:10 UTC, hertneky commented on scripts/run_upp
>  elif [[ ${model} == "LAM" ]]; then
inFormat for LAM can also be netcdfpara

2022-05-05 16:10 UTC, hertneky commented on scripts/run_upp
> +export UNIPOST_HOME=${TOP_DIR}/UPP
Could consider changing UNIPOST_HOME to UPP_HOME here and throughout.
 (L38, 67, 68, 198-199, 204-205, 208)

2022-05-05 16:34 UTC, kayeekayee commented
> 

Yes, this changes has been tested on Cheyenne with Intel compiler for all the netcdf and netcdfpara cases. 
Here is the test path: /glade/scratch/kayee/UPP/UFFDA/UFFDA

2022-05-05 17:44 UTC, hertneky approved these changes
One super minor formatting change

@fossell Do we know if the GFS model output names are the same with the transition to the global workflow for MRW? The current/old MRW release model output filenames are atmfhhh.nc/sfcfhhh.nc.

2022-05-05 17:44 UTC, hertneky commented on scripts/run_upp
> +# UPP_HOME  : Location of the UPP directory
Formatting here to match the rest of the list

2022-05-05 20:20 UTC, fossell approved these changes

2022-05-05 20:22 UTC, fossell commented
> 

Good question, I can ask and we can update if needed. This PR can go ahead as-is to expedite release testing. We can update again once more information is gathered.

2022-05-05 21:12 UTC, hertneky requested changes

2022-05-05 21:12 UTC, hertneky commented on scripts/run_upp
>        flxFileName=${modelDataPath}/dynf${fhour}.nc
change to flxFileName=${modelDataPath}/phyf${fhour}.nc

2022-05-09 16:14 UTC, fossell commented
@kayeekayee - What is the status on this testing with these final updates? Has it been run through all cases or just confirmed in a single standalone test?
@hertneky - Can you review the final updates Ka Yee made in response to your requested changes?

2022-05-09 17:35 UTC, kayeekayee commented
@fossell I tested 6 cases including netcdfpara with Intel compiler.

2022-05-09 18:42 UTC, fossell commented
> @fossell I tested 6 cases including netcdfpara with Intel compiler.

Great! Then I think this should be ok to merge. We'll wait for @hertneky to give her final approval on the PR though.

2022-05-10 18:40 UTC, hertneky approved these changes
I keep finding more things every time I review, but this is the last one, I swear! We can either link the 9.0.1 release or the soon-to-be released 10.0.12, probably the latter

2022-05-10 18:40 UTC, hertneky commented on scripts/run_upp
>        flxFileName=${modelDataPath}/dynf${fhour}.nc
change to flxFileName=${modelDataPath}/phyf${fhour}.nc

2022-05-10 18:40 UTC, hertneky commented on scripts/run_upp
>  #----------------------------------------------------------------------------------
Link on L38 for the UPP Usres Guide does not work - let's get this updated

2022-05-10 18:54 UTC, fossell commented on scripts/run_upp
>  #----------------------------------------------------------------------------------
Good catch. What about changing to https://upp.readthedocs.io/en/latest/ since we control what is "latest" on ReadTheDocs?

2022-05-10 19:06 UTC, hertneky commented on scripts/run_upp
>  #----------------------------------------------------------------------------------
That works too. I think the only place latest is linked is on the wiki and points to develop currently.

2022-05-10 20:31 UTC, merged