fixed the UPP crash in Atmos
NOAA-EMC/UPP pull request #525
Opened 2022-06-21 13:32 UTC by lipan-NOAA

@WenMeng-NOAA @XianwuXue-NOAA @zhanglikate @bbakernoaa @rmontuoro 

For the issue #524

2022-06-21 19:42 UTC, WenMeng-NOAA commented
@lipan-NOAA After this PR merged, how would you like the tag name convention for NCO implementation, re-creating gefs_v12.3.0 or creating gefs_v12.3.1? Also I assume the fix would not be applied in develop branch for gefs V13 development, right?

2022-06-21 20:22 UTC, XianwuXue-NOAA commented
> @lipan-NOAA After this PR merged, how would you like the tag name convention for NCO implementation, re-creating gefs_v12.3.0 or creating gefs_v12.3.1? Also I assume the fix would not be applied in develop branch for gefs V13 development, right?

Please re-creating gefs_v12.3.0. Thanks @WenMeng-NOAA

2022-06-21 20:24 UTC, XianwuXue-NOAA requested changes

2022-06-21 20:24 UTC, XianwuXue-NOAA commented on sorc/ncep_post.fd/INITPOST_GFS_NEMS_MPIIO.f
> +       call assignnemsiovar(im,jsta,jend,jsta_2l,jend_2u    &
Could you update the codes to the original one with same indents? Because you didn't change these codes.

2022-06-21 23:01 UTC, lipan-NOAA commented
@WenMeng-NOAA let me test develop branch this weekend. I am preparing for CCB meeting this Friday.

2022-06-22 13:58 UTC, WenMeng-NOAA commented on sorc/ncep_post.fd/INITPOST_GFS_NEMS_MPIIO.f
> +       call assignnemsiovar(im,jsta,jend,jsta_2l,jend_2u    &
@lipan-NOAA Could you update your PR based on @XianwuXue-NOAA 's comment? Thanks!

2022-06-22 22:57 UTC, lipan-NOAA commented on sorc/ncep_post.fd/INITPOST_GFS_NEMS_MPIIO.f
> +       call assignnemsiovar(im,jsta,jend,jsta_2l,jend_2u    &
@WenMeng-NOAA @XianwuXue-NOAA I changed it.

2022-06-23 13:45 UTC, WenMeng-NOAA approved these changes

2022-06-23 13:51 UTC, merged

2022-06-23 13:59 UTC, WenMeng-NOAA commented
@lipan-NOAA and @XianwuXue-NOAA The tag gefs_v12.3.0 was recreated.

2022-06-23 14:53 UTC, lipan-NOAA commented
@WenMeng-NOAA Thanks a lot